### ISSUE TITLE
support for HA statistics: add state_class

### ISSUE THREAD

**Issue by wivaku** [metbril/home-assistant-brandstofprijzen#12]
Could you add `state_class: measurement` to the sensors so it can be used for the recently added statistics functionality in HA?

https://www.home-assistant.io/more-info/statistics/

**Comment by metbril** [comment]
Note to self. Add property `state_class` with value `measurement`.

https://developers.home-assistant.io/docs/core/entity/sensor/#value-entities---entities-not-representing-a-total-amount

**Comment by kacper-serewis** [comment]
Can this be applied?

**Comment by metbril** [comment]
Issue has been open for too long. Any pull requests are still welcome.

**Comment by vincentnk** [comment]
I added a pull request for this feature. I'm by no means an experienced developer tho, so feel free to suggest any improvements to the pull request.
I tested this change on my home assistant instance, where I now have long term statistics for the sensors.

**Comment by metbril** [comment]
Reopened.

**Comment by TommiieeSV** [comment]
For anyone reading this, I have solved this problem (long term statistics) by looking at the closed PR above, combined with some help from ChatGPT. I have manually edited the `sensor.py` in `/custom_components/brandstofprijzen` to look like this:

```python
"""Brandstofprijzen Sensors."""

import logging
from datetime import datetime, timedelta

import homeassistant.helpers.config_validation as cv
import requests
import voluptuous as vol
from homeassistant.components.sensor import (
    PLATFORM_SCHEMA,
    SensorEntity,
    SensorStateClass,
)
from homeassistant.const import (
    ATTR_ATTRIBUTION,
    CONF_ICON,
    CONF_MONITORED_VARIABLES,
    CONF_PREFIX,
    CONF_SCAN_INTERVAL,
    CONF_UNIT_OF_MEASUREMENT,
)
from homeassistant.util import Throttle

REQUIREMENTS = ["beautifulsoup4==4.13.4"]

_LOGGER = logging.getLogger(__name__)
_RESOURCE = "https://www.unitedconsumers.com/tanken/brandstofprijzen"

_USERAGENT = "UnitedConsumers Brandstofprijzen for Home Assistant"

ATTRIBUTION = "Data provided by UnitedConsumers"
DEFAULT_ICON = "mdi:gas-station"
DEFAULT_PREFIX = "Adviesprijs"
DEFAULT_UNIT_OF_MEASUREMENT = "€/L"

# Prevent hammering the webpage, prices usually change once a day
DEFAULT_SCAN_INTERVAL = timedelta(hours=1)
# Prevent fetching the page again for each sensor
MIN_TIME_BETWEEN_UPDATES = timedelta(minutes=1)

# All fuel types on the page, in page order.
SENSOR_TYPES = {
    "euro95": ["Euro95"],
    "diesel": ["Diesel"],
    "lpg": ["LPG"],
    "super": ["Super"],
    "super_mlv": ["Super MLV"],
    "premium_benzines": ["Premium benzines"],
    "premium_diesels": ["Premium diesels"],
}

PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend(
    {
        vol.Optional(CONF_MONITORED_VARIABLES, default=list(SENSOR_TYPES)): vol.All(
            cv.ensure_list, [vol.In(SENSOR_TYPES)]
        ),
        vol.Optional(CONF_ICON, default=DEFAULT_ICON): cv.string,
        vol.Optional(
            CONF_UNIT_OF_MEASUREMENT, default=DEFAULT_UNIT_OF_MEASUREMENT
        ): cv.string,
        vol.Optional(CONF_PREFIX, default=DEFAULT_PREFIX): cv.string,
        vol.Optional(CONF_SCAN_INTERVAL, default=DEFAULT_SCAN_INTERVAL): cv.time_period,
    }
)


def setup_platform(hass, config, add_devices, discovery_info=None):
    """Set up the Brandstofprijzen sensor."""
    scan_interval = config[CONF_SCAN_INTERVAL]
    rest = BrandstofprijzenData(_RESOURCE)
    if config[CONF_MONITORED_VARIABLES] == []:
        config[CONF_MONITORED_VARIABLES] = SENSOR_TYPES
    variables = []
    for variable in config[CONF_MONITORED_VARIABLES]:
        variables.append(BrandstofprijzenSensor(variable, rest, config))
    add_devices(variables, True)


class BrandstofprijzenSensor(SensorEntity):
    """Implementing the Brandstofprijzen sensor."""

    def __init__(self, sensor_type, rest, config):
        """Initialize the sensor."""
        self._name = config[CONF_PREFIX].rstrip() + " " + SENSOR_TYPES[sensor_type][0]
        self._unit_of_measurement = config[CONF_UNIT_OF_MEASUREMENT]
        self._icon = config[CONF_ICON]
        self.rest = rest
        self.type = sensor_type
        self._state = None

    @property
    def name(self):
        """Return the name."""
        return self._name

    @property
    def icon(self):
        """Return the icon."""
        return self._icon

    @property
    def native_value(self):
        """Return the state."""
        return self._state

    @property
    def native_unit_of_measurement(self):
        """Return the unit of measurement."""
        return self._unit_of_measurement
        
    @property
    def state_class(self):
        """Return the state class."""
        return SensorStateClass.MEASUREMENT

    @property
    def extra_state_attributes(self):
        """Return the state attributes."""
        return {ATTR_ATTRIBUTION: ATTRIBUTION}

    @property
    def available(self):
        """Could the device be accessed during the last update call."""
        return self.rest.available

    def update(self):
        """Update current date."""
        self.rest.update()
        for idx, stype in enumerate(SENSOR_TYPES):
            if self.type == stype:
                try:
                    self._state = self.rest.data[idx]
                    _LOGGER.debug("Updated sensor %s to %.3f", self.type, self._state)
                except (TypeError, IndexError):
                    self._state = None
                    _LOGGER.error("Unable to update %s", self.type)


class BrandstofprijzenData(object):
    """Get data from site."""

    def __init__(self, sensor):
        """Initialize the data object."""
        self._sensor = sensor
        self.data = None
        self.available = True

    @Throttle(MIN_TIME_BETWEEN_UPDATES)
    def update(self):
        """Get the latest data."""
        from bs4 import BeautifulSoup

        headers = {"User-Agent": _USERAGENT}
        try:
            r = requests.get(self._sensor, headers=headers, timeout=10)
            soup = BeautifulSoup(r.text, "html.parser")

            price_elements = soup.select('span[data-sentry-component="Price"]')

            data = []
            for idx, el in enumerate(price_elements):
                text = el.get_text(strip=True)
                if "€" in text:
                    try:
                        value = float(text.replace("€", "").replace(",", ".").strip())
                        data.append(value)
                    except ValueError:
                        _LOGGER.warning(f"Kon geen getal maken van prijs: {text}")
                else:
                    _LOGGER.warning(f"[{idx}] Geen euro-teken in tekst: '{text}'")

            self.data = data
            self.available = True
            _LOGGER.debug(f"Geparsed prijzen: {data}")
        except requests.exceptions.ConnectionError:
            _LOGGER.error("Connection error")
            self.data = None
            self.available = False
```

Don't forget to restart Home Assistant. It will now build up statistics. If you use ApexCharts for example, it will take at least 11 days for this change to become visible, because for the last 10 days it uses history and for everything before that it will use the statistics.

My ApexChart for brandstofprijzen looks like this (just for reference):

```yaml
type: custom:apexcharts-card
graph_span: 1 month
header:
  show: true
  show_states: true
  colorize_states: true
yaxis:
  - id: Price
    opposite: true
    decimals: 3
    apex_config:
      labels:
        formatter: |
          EVAL:function(value) {
            return '€' + value.toFixed(2);
          }
apex_config:
  xaxis:
    labels:
      datetimeUTC: false
      format: dd MMM yyyy
  tooltip:
    enabled: true
    shared: true
    intersect: false
    x:
      format: dd MMM yyyy
    "y":
      formatter: |
        EVAL:function(value) {
          return '€' + value.toFixed(3);
        }
  stroke:
    curve: smooth
    width: 3
  legend:
    show: false
    position: bottom
    horizontalAlign: center
series:
  - entity: sensor.adviesprijs_diesel
    float_precision: 3
    statistics:
      type: mean
      period: day
    group_by:
      func: last
      duration: 1d
  - entity: sensor.adviesprijs_premium_diesels
    float_precision: 3
    statistics:
      type: mean
      period: day
    group_by:
      func: last
      duration: 1d
  - entity: sensor.adviesprijs_euro95
    float_precision: 3
    statistics:
      type: mean
      period: day
    group_by:
      func: last
      duration: 1d
```

@metbril I am no developer, so I am unable to provide a PR. Would you be able to update the integration yourself with the updated sensor.py?
