### ISSUE TITLE
Keep getting error: "Message malformed: extra keys not allowed @ data['automation']" when trying to save automation

### ISSUE THREAD

**Issue by nielssteenvoorde** [metbril/home-assistant-brandstofprijzen#25]
I was getting United Consumers working within HACS. This is working oke. Than I added in configuration.yaml the sensor:
 ```
sensor:
  - platform: brandstofprijzen
```

Did try the extensive sensor too.
```
sensor:
  - platform: brandstofprijzen
    monitored_variables:
      - euro95
      - diesel
      - lpg
      - super
      - super_mlv
      - premium_benzines
      - premium_diesels
    icon: mdi:gas-station
    unit_of_measurement: €/L
    prefix: Adviesprijs
    scan_interval:
        hours: 1
```

Didn't work either.

Restarted HA after adjustment. After this I wanted to add the automation (changed automation screen to yaml) and paste the text:
```
automation:
  - alias: "Melding bij gewijzigde brandstofprijzen"
    id: brandstofprijzen_update_notification
    description: >
      Send notification when a fuel price changed
    trigger:
      - platform: state
        entity_id:
          - sensor.adviesprijs_euro95
          - sensor.adviesprijs_diesel
          - sensor.adviesprijs_lpg
          - sensor.adviesprijs_super
          - sensor.adviesprijs_super_mlv
          - sensor.adviesprijs_premium_benzines
          - sensor.adviesprijs_premium_diesels
    condition: "{{ trigger.state.to_state != trigger.state.from_state }}"
    action:
      - service: notify.notify
        data:
          title: Adviesprijs gewijzigd
          message: >
            De adviesprijs voor
            {{ state_attr(trigger.entity_id, 'friendly_name') }}
            is
            {% if trigger.state.to_state > trigger.state.from_state %}
              verhoogd.
            {% else %}
              verlaagd.
            {% endif %}
    mode: queued
```
When wanted to save the automation I'll keep getting the message:
```
Message malformed: extra keys not allowed @ data['automation']
```
In log files there are no clues

The HA is running on a RPI4 from an SSD stick
```
Core: 2024.1.3
Supervisor: 2023.12.0
Operating System: 11.4
Frontend: 20240104.0
```
Editing in Chrome browser on a Windows 11 machine

Strange thing is happening for the other fuel addon: dutch gas prices too. I don't get it. Is it because of the new version of HA that the functionality data doesn't work anymore?

**Comment by metbril** [comment]
Hi. What version of the United Consumers integration are you using?

To be able to help you troubleshoot, you should edit your issue and put 3 backticks (`` ``` ``) both before and after your configuration.

Are there any errors when you check you configuration?

**Comment by nielssteenvoorde** [comment]
I'm using v0.4 of United Consumers. 

I think I now put the backticks in the wright way ;-)

**Comment by metbril** [comment]
From the error message it looks like you added the line "automation:" where you shouldn't. If you paste the automation in the automation editor you should leave that line out. You can have it only once in the file at the top.

**Comment by nielssteenvoorde** [comment]
> From the error message it looks like you added the line "automation:" where you shouldn't. If you paste the automation in the automation editor you should leave that line out. You can have it only once in the file at the top.

Is not working.

first step:
![United Consumers toevoegen automation](https://github.com/metbril/home-assistant-brandstofprijzen/assets/34322760/ad4f84df-d4cf-4ac7-841e-0ee65b65758c)

second step:
![United Consumers bewerking YAML](https://github.com/metbril/home-assistant-brandstofprijzen/assets/34322760/731c2c2e-6a23-4e99-9abc-cd938fa55fa7)

third step (without automation:):
![United Consumers (excl automation)](https://github.com/metbril/home-assistant-brandstofprijzen/assets/34322760/e7745a38-033f-4abd-86e4-ee3d5e4645a7)

third step (with automation:)
![United Consumers (incl automation)](https://github.com/metbril/home-assistant-brandstofprijzen/assets/34322760/6329a6b2-1e9a-40dc-b73c-b5c02f7f197c)

Both methods give the same error message:
```
Message malformed: extra keys not allowed @ data['automation']
```

I still can't get it to work. Does it had something to do with the new version of HA that skipped "data" perhaps?

**Comment by metbril** [comment]
Please try to replace  the hyphen before "alias" with a space. The automation should be left aligned without any leading hyphens. Open one of your other automations as yaml to see what I mean.

**Comment by nielssteenvoorde** [comment]
I think it now works. I did change the automation text in: 
```
alias: Melding bij gewijzigde brandstofprijzen
description: |
  Send notification when a fuel price changed
trigger:
  - platform: state
    entity_id:
      - sensor.adviesprijs_euro95
      - sensor.adviesprijs_diesel
      - sensor.adviesprijs_lpg
      - sensor.adviesprijs_super
      - sensor.adviesprijs_super_mlv
      - sensor.adviesprijs_premium_benzines
      - sensor.adviesprijs_premium_diesels
condition:
  - condition: template
    value_template: "{{ trigger.state.to_state != trigger.state.from_state }}"
action:
  - service: notify.notify
    data:
      title: Adviesprijs gewijzigd
      message: >
        De adviesprijs voor {{ state_attr(trigger.entity_id, 'friendly_name') }}
        is {% if trigger.state.to_state > trigger.state.from_state %}
          verhoogd.
        {% else %}
          verlaagd.
        {% endif %}
mode: queued
```
Now hoping for lower prices here in the Netherlands ;-)
